/*
MAGNITUDE ANALYSIS

compares the measure values by categries

it helps us to understand the importance of different categories*/

--find the total no-of customers by country
select
country,
count(customer_key) total_customers
from gold.dim_customer
group by country
order by total_customers desc

--find total no-of customers by gender
select
gender,
count(customer_key) total_customers
from gold.dim_customer
group by gender
order by total_customers desc

--find total products by category
select
category,
count(product_key) total_products
from gold.dim_product
group by category
order by total_products desc

--find average cost in each category
select
category,
avg(cost) average_cost
from gold.dim_product
group by category
order by average_cost desc

--what is the total revenue generated by each category
select
p.category,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_product p
on f.product_key = p.product_key
group by category
order by total_revenue desc

--what are the total revenue generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_customer c
on f.product_key = c.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc

--what is the distrubution of sold items across country
select
c.country,
sum(f.quantity) total_sold_items
from gold.fact_sales f
left join gold.dim_customer c
on f.product_key = c.customer_key
group by c.country
order by total_sold_items desc
